from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib import colors
from datetime import date
from io import BytesIO
import matplotlib.pyplot as plt
import pandas as pd


def fig_to_img(fig) -> BytesIO:
    """Convert a matplotlib figure to an in-memory image buffer."""
    buf = BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight")
    plt.close(fig)
    buf.seek(0)
    return buf


def generate_insight_report(
    regions: str,
    date_range: str,
    correlation_df: pd.DataFrame,
    scatter_fig,
    boxplot_fig,
    output_path: str = "reports/scientific_insight_report.pdf"
) -> str:
    doc = SimpleDocTemplate(output_path, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    # Title & Metadata
    elements.append(Paragraph("📘 <b>Wine Quality Insights Report</b>", styles['Title']))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph(f"<b>Analyzed Regions:</b> {regions}", styles['Normal']))
    elements.append(Paragraph(f"<b>Date Range:</b> {date_range}", styles['Normal']))
    elements.append(Spacer(1, 12))

    # Section: Correlation Table
    elements.append(Paragraph("🔬 <b>Top Correlated Features</b>", styles['Heading2']))
    elements.append(Spacer(1, 6))

    corr_df_clean = correlation_df.dropna().round(3).sort_values(
        by="Correlation", key=abs, ascending=False
    )
    table_data = [["Feature", "Correlation"]] + corr_df_clean.reset_index().values.tolist()

    table = Table(table_data, hAlign="LEFT", colWidths=[300, 100])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('GRID', (0, 0), (-1, -1), 0.25, colors.grey),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 20))

    # Section: Plots
    elements.append(Paragraph("📈 <b>Correlation Scatter Plot</b>", styles['Heading2']))
    elements.append(Image(fig_to_img(scatter_fig), width=5.5 * inch, height=3.5 * inch))
    elements.append(Spacer(1, 20))

    elements.append(Paragraph("📊 <b>KPI Box Plot</b>", styles['Heading2']))
    elements.append(Image(fig_to_img(boxplot_fig), width=5.5 * inch, height=3.5 * inch))
    elements.append(Spacer(1, 20))

    # Footer
    elements.append(Paragraph(f"🧑‍🔬 Report generated by Baltzakis Themistoklis", styles['Normal']))
    elements.append(Paragraph(f"📅 Date: {date.today().isoformat()}", styles['Normal']))

    doc.build(elements)
    return output_path

