kpi_descriptions = {
    "dew_point_2m": "Temperature at which air reaches saturation (humidity marker)",
    "wet_bulb_temperature_2m": "Temperature accounting for evaporation cooling effect",
    "temperature_2m": "Standard air temperature at 2 meters above surface",
    "temperature_2m_mean": "Average daily air temperature at 2 meters",
    "relative_humidity_2m": "Percentage of moisture in air compared to max capacity",
    "cloud_cover": "Fraction of sky obscured by clouds",
    "cloud_cover_high": "Coverage by high-altitude clouds",
    "precipitation_sum": "Total precipitation over a period",
    "total_column_integrated_water_vapour": "Vertical total of atmospheric water vapor",
    "et0_fao_evapotranspiration": "FAO Penman-Monteith evapotranspiration estimate",
    "pressure_msl": "Atmospheric pressure at mean sea level",
    "surface_pressure": "Actual pressure at the Earth's surface",
    "wind_speed_10m": "Horizontal wind speed at 10 meters",
    "wind_direction_10m": "Wind direction (degrees) at 10 meters",
    "apparent_temperature": "Feels-like temperature combining wind & humidity",
    "soil_temperature_0_to_7cm": "Top-layer soil temperature",
    "soil_moisture_0_to_7cm": "Top-layer soil moisture content",
    "rain": "Rainfall depth",
    "snowfall": "Accumulated snowfall",
    "vapour_pressure_deficit": "Drying power of air – gap between vapor pressure & saturation",
    "shortwave_radiation": "Solar radiation reaching the surface (W/m²)",
    "sunshine_duration": "Hours of sunlight per day",
    "wine_quality_score": "Predicted quality score of wine based on features"
}
